name: Publish cleaned blog post from drafts (Gemini 2.5 Pro)

on:
  schedule:
    - cron: "0 6 * * 2"   # Tue 09:00 Asia/Jerusalem = 06:00 UTC
    - cron: "0 6 * * 5"   # Fri 09:00 Asia/Jerusalem = 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find latest draft
        id: draft
        run: |
          set -e
          if [ -z "$(ls -A drafts 2>/dev/null)" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          latest="$(ls -1t drafts | head -n 1)"
          echo "file=$latest" >> $GITHUB_OUTPUT
          echo "Found draft: $latest"

      - name: Stop if no draft
        if: steps.draft.outputs.skip == 'true'
        run: echo "No drafts to publish."

      - name: Read draft contents
        id: read
        if: steps.draft.outputs.skip != 'true'
        run: |
          # JSON-safe string for the API payload
          jq -Rs . < "drafts/${{ steps.draft.outputs.file }}" > draft.json
          echo "Draft bytes: $(wc -c < draft.json)"

      - name: Generate polished post with Gemini 2.5 Pro
        if: steps.draft.outputs.skip != 'true'
        id: llm
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLE_API }}   # repo secret
        run: |
          set -e
          today=$(date -u +"%Y-%m-%d")
          raw=$(cat draft.json)   # JSON string of the draft text

          # Build request for REST API
          body=$(jq -n --arg raw "$raw" '{
            systemInstruction: {
              role: "system",
              parts: [{text: "You are a concise editor for a developer’s public learning log. Keep the author’s voice human and informal. Turn raw notes into a short Markdown blog post (250–450 words) with: a strong H1 title, a crisp intro, 3–6 bullet points for key learnings/struggles, a short reflection, and a one-line Next at the end. Add 4–6 tags as a comma list at the bottom. Output valid Markdown only."}]
            },
            contents: [
              {
                role: "user",
                parts: [{text: ("RAW NOTES:\n" + ($raw | fromjson))}]
              }
            ],
            generationConfig: {temperature: 0.6}
          }')

          # Call Gemini (v1beta REST)
          curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent?key=${GEMINI_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "$body" > out.json

          # If API returned an error, show it and fail
          err=$(jq -r '.error.message // empty' out.json)
          if [ -n "$err" ]; then
            echo "Gemini error:"; cat out.json; exit 1
          fi

          # Assemble Markdown from all text parts
          text=$(jq -r '[.candidates[0].content.parts[]?.text] | join("\n")' out.json)
          if [ -z "$text" ] || [ "$text" = "null" ]; then
            echo "Model returned empty text"; cat out.json; exit 1
          fi

          # Derive title and slug
          title=$(echo "$text" | grep -m1 '^# ' | sed 's/^#\s*//' || true)
          if [ -z "$title" ]; then title=$(echo "$text" | head -n1 | sed 's/[#*]*\s*//'); fi
          if [ -z "$title" ]; then title="Untitled"; fi

          slug=$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')
          if [ -z "$slug" ]; then slug="post"; fi

          # Remove H1 (Jekyll prints title from front matter)
          body_md=$(echo "$text" | sed '1{/^# /d;}')

          # Normalize the title a bit (straight quotes, no weird dashes)
          title=$(echo "$title" | sed 's/[“”]/"/g; s/[’]/'"'"'/g; s/—/-/g')

          # Write post
          outfile="_posts/${today}-${slug}.md"
          cat > "$outfile" <<EOF
          ---
          layout: post
          title: "$title"
          date: $today
          ---
          $body_md
          EOF
          echo "Wrote $outfile"
          echo "outfile=$outfile" >> $GITHUB_OUTPUT

      - name: Archive used draft
        if: steps.draft.outputs.skip != 'true'
        run: |
          mkdir -p archived_drafts
          mv "drafts/${{ steps.draft.outputs.file }}" "archived_drafts/"
          echo "Archived drafts/${{ steps.draft.outputs.file }}"

      - name: Commit & push
        if: steps.draft.outputs.skip != 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts archived_drafts
          git commit -m "Publish: ${{ steps.llm.outputs.outfile }}"
          git push
